name: openmm-jax
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - cmake>=3.22
  - make
  - cxx-compiler
  - swig=4.3.1
  - cuda-version=12.9
  - cuda-cudart-dev
  - cuda-driver-dev
  - cuda-crt=12.9.86
  - openmm=8.5.2
  - openmm-ml=1.7
  - openmmforcefields=0.15.1
  - openff-toolkit
  - ambertools
  - mdtraj
  - matplotlib
  - numpy
  - pip:
      - -r requirements.txt
      - jax==0.10.1
      - jaxlib==0.10.1
      - jax-cuda12-plugin==0.10.1
      - jax-cuda12-pjrt==0.10.1
      - jax-md>=0.2.29
      - equinox==0.13.8
      - fennol==2026.5.7
