# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _openmmjax
else:
    import _openmmjax

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import openmm.openmm
class JaxForce(openmm.openmm.Force):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, forceMlir, energyMlir, energyAndForcesMlir, compileOptionsBase64):
        _openmmjax.JaxForce_swiginit(self, _openmmjax.new_JaxForce(forceMlir, energyMlir, energyAndForcesMlir, compileOptionsBase64))

    def getForceMlir(self):
        return _openmmjax.JaxForce_getForceMlir(self)

    def getEnergyMlir(self):
        return _openmmjax.JaxForce_getEnergyMlir(self)

    def getEnergyAndForcesMlir(self):
        return _openmmjax.JaxForce_getEnergyAndForcesMlir(self)

    def getCompileOptions(self):
        return _openmmjax.JaxForce_getCompileOptions(self)

    def getCompileOptionsBase64(self):
        return _openmmjax.JaxForce_getCompileOptionsBase64(self)

    def setUsesPeriodicBoundaryConditions(self, periodic):
        return _openmmjax.JaxForce_setUsesPeriodicBoundaryConditions(self, periodic)

    def usesPeriodicBoundaryConditions(self):
        return _openmmjax.JaxForce_usesPeriodicBoundaryConditions(self)

    def setOutputsForces(self, arg2):
        return _openmmjax.JaxForce_setOutputsForces(self, arg2)

    def getOutputsForces(self):
        return _openmmjax.JaxForce_getOutputsForces(self)

    def setPjrtPluginPath(self, path):
        return _openmmjax.JaxForce_setPjrtPluginPath(self, path)

    def getPjrtPluginPath(self):
        return _openmmjax.JaxForce_getPjrtPluginPath(self)

    def setForceGroup(self, group):
        return _openmmjax.JaxForce_setForceGroup(self, group)

    def getForceGroup(self):
        return _openmmjax.JaxForce_getForceGroup(self)

    def addToSystem(self, system):
        return _openmmjax.JaxForce_addToSystem(self, system)

    @staticmethod
    def cast(force):
        return _openmmjax.JaxForce_cast(force)

    @staticmethod
    def isinstance(force):
        return _openmmjax.JaxForce_isinstance(force)
    __swig_destroy__ = _openmmjax.delete_JaxForce

# Register JaxForce in _openmmjax:
_openmmjax.JaxForce_swigregister(JaxForce)


_JaxForce_addToSystem = JaxForce.addToSystem

def _jax_force_add_to_system(self, system):
    index = _JaxForce_addToSystem(self, system)
    self.thisown = False
    return index

JaxForce.addToSystem = _jax_force_add_to_system



